---
name: Spring Football service Clean - REST (curl)
author: David Kopp
description: Executes individual API requests using curl
ignore-unsupported-compose: true

compose-file: !include docker/compose.yml

services:
  
  # change container names so GMT can compare results between simple and clean
  service:
    container_name: service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5438/postgres
      SERVER_HTTP2_ENABLED: false

  db:
    container_name: database

  curl:
    container_name: curl
    image: curlimages/curl:8.1.0
    command: sh
    depends_on:
      service:
        condition: service_healthy # wait until the service is ready before starting with the flow

sci:
  R_d: API Call

flow:
  - name: Get player by id
    container: curl
    commands:
      - type: console
        command: curl -s service:8088/players/1
        note: Get player
      - type: console
        command: echo GMT_SCI_R=1
        log-stdout: true
        read-sci-stdout: true

  - name: Get player records by id
    container: curl
    commands:
      - type: console
        command: curl -s service:8088/players/record/1
        note: Get player record
      - type: console
        command: echo GMT_SCI_R=1
        log-stdout: true
        read-sci-stdout: true
