---
name: Spring Football service Clean - REST (Artillery)
author: David Kopp
description: Executes a HTTP load test scenario using Artillery. There are two phases, warm up and constant load.

compose-file: !include docker/compose.yml

services:

  # change container names so GMT can compare results between simple and clean
  service:
    container_name: service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5438/postgres
      SERVER_HTTP2_ENABLED: false

  db:
    container_name: database

  artillery:
    container_name: artillery
    image: artilleryio/artillery:2.0.20 # 2.0.21 has a bug, 2.0.22 is much bigger (Alpine -> Debian + Chromium for Playwright)
    depends_on:
      service:
        condition: service_healthy # wait until the service is ready before starting with the flow
    entrypoint: "" # ignore default entrypoint
    command: sleep infinity # wait for commands in the flow

flow:
  - name: Warm Up
    container: artillery
    commands:
      - type: console
        command: run run /tmp/repo/client/artillery_gmt_warm_up.yml -t http://service:8088 # first run is the executable, second run the artillery command 'run'
        log-stdout: true
        log-stderr: true
  - name: Load Test
    container: artillery
    commands:
      - type: console
        command: run run /tmp/repo/client/artillery_gmt_load.yml -t http://service:8088 # first run is the executable, second run the artillery command 'run'
        log-stdout: true
        log-stderr: true
