---
name: Spring Football service Clean - REST (k6)
author: David Kopp
description: Executes a HTTP load test scenario using K6. There are two phases, warm up and constant load. An open workload scenario is used with a peak of 400 requests per second.

compose-file: !include docker/compose.yml

services:

  # change container names so GMT can compare results between simple and clean
  service:
    container_name: service
    environment:
      DATASOURCES_FOOTBALL_DATASOURCE_URL: jdbc:postgresql://database:5438/postgres
      SERVER_HTTP2_ENABLED: false

  db:
    container_name: database

  k6:
    container_name: k6
    image: grafana/k6:0.57.0
    depends_on:
      service:
        condition: service_healthy # wait until the service is ready before starting with the flow
    entrypoint: "" # ignore default entrypoint
    command: sleep infinity # wait for commands in the flow
    environment:
      TARGET_HOSTNAME: "service:8088"

flow:
  - name: Warm Up
    container: k6
    commands:
      - type: console
        command: k6 run /tmp/repo/client/k6_http_gmt_warm_up.js --quiet
        log-stdout: true # only summary is logged
        log-stderr: true
  - name: Constant Load
    container: k6
    commands:
      - type: console
        command: k6 run /tmp/repo/client/k6_http_gmt_load.js --quiet
        log-stdout: true # only summary is logged
        log-stderr: true
