receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "otel-col:4317"
      http:
        endpoint: "otel-col:4318"

exporters:
  prometheus:
    endpoint: "otel-col:9464"

processors:
  batch:

connectors:
  spanmetrics:
    histogram:
      explicit:
        buckets: [2ms, 8ms, 50ms, 100ms, 200ms, 500ms, 1s, 2s, 5s, 10s]
    dimensions:
      - name: http.route
      - name: rpc.service
      - name: rpc.method
    metrics_flush_interval: 1s

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [spanmetrics]
    metrics:
      receivers: [otlp, spanmetrics]
      processors: [batch]
      exporters: [prometheus]
