syntax = "proto3";
option java_multiple_files = true;
option java_package = "de.envite.sample.spring.clean.football.proto";
option java_outer_classname = "PlayerServiceProto";

service Player {
  rpc GetPlayerById (PlayerIdRequest) returns (PlayerReply) {}
  rpc GetPlayerRecordById (PlayerIdRequest) returns (PlayerRecordReply) {}
}

message PlayerIdRequest {
  sint64 id = 1;
}

message PlayerReply {
  sint64 id = 1;
  int32 playerApiId = 2;
  int32 playerFifaApiId = 3;
  string playerName = 4;
  string birthday = 5;
  int32 height = 6;
  int32 weight = 7;
}

message PlayerAttributes {
  sint64 id = 1;
  string date = 2;
  optional int32 overallRating = 3;
  optional int32 potential = 4;
  optional string preferredFoot = 5;
  string attackingWorkRate= 6;
  string defensiveWorkRate = 7;
  optional int32 crossing = 8;
  optional int32 finishing = 9;
  optional int32 headingAccuracy = 10;
  optional int32 shortPassing = 11;
  optional int32 volleys = 12;
  optional int32 dribbling = 13;
  optional int32 curve = 14;
  optional int32 freeKickAccuracy = 15;
  optional int32 longPassing = 16;
  optional int32 ballControl = 17;
  optional int32 acceleration = 18;
  optional int32 sprintSpeed = 19;
  optional int32 agility = 20;
  optional int32 reactions = 21;
  optional int32 balance = 22;
  optional int32 shotPower = 23;
  optional int32 jumping = 24;
  optional int32 stamina = 25;
  optional int32 strength = 26;
  optional int32 longShots = 27;
  optional int32 aggression = 28;
  optional int32 interceptions = 29;
  optional int32 positioning = 30;
  optional int32 vision = 31;
  optional int32 penalties = 32;
  optional int32 marking = 33;
  optional int32 standingTackle = 34;
  optional int32 slidingTackle = 35;
  optional int32 gkDiving = 36;
  optional int32 gkHandling = 37;
  optional int32 gkKicking = 38;
  optional int32 gkPositioning = 39;
  optional int32 gkReflexes = 40;
}

message PlayerRecordReply {
  PlayerReply player = 1;
  repeated PlayerAttributes attributes = 2;
}