spring:
  application:
    name: "spring-rest-clean-football-service"
  threads:
    virtual:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/XXX
    username: YYY
    password: ZZZ
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 90 # default: 10
  flyway:
    locations: classpath:db/migration
  data:
    jdbc:
      repositories:
        enabled: true
server:
  tomcat:
    max-keep-alive-requests: -1
  http2:
    enabled: true # required for gRPC
  port: 8080

logging:
  level:
    org.springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-components: always
      show-details: always
