name: spring-clean-football-service

services:

  service:
    container_name: spring-clean-football-service
    platform: linux/amd64
    image: registry.gitlab.com/envite-consulting/sustainable-software-architecture/isaqb-green/spring-clean-football-service:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-clean-service:5438/postgres
      SPRING_PROFILES_ACTIVE: "secure"
      THC_PATH: /actuator/health
      THC_PORT: 8088
      MATCH_REST_TEAM_NAME_STRATEGY: POJO_WITH_CACHE
      MATCH_REST_TEAM_SERVICE_BASE_URL: http://service:8088
      SPRING_FLYWAY_ENABLED: "false"
    ports:
      - "8088:8088"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "/workspace/health-check"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  db:
    container_name: postgres-db-clean-service
    platform: linux/amd64
    image: registry.gitlab.com/envite-consulting/sustainable-software-architecture/football-databases:postgres-17.7 # use pre-built image with data to save time at startup
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5438:5438"
    command: -p 5438
    healthcheck:
      test: "pg_isready -p 5438 -U postgres"
      start_period: "30s"
      start_interval: "1s"
      interval: "24h" # only the start is relevant for us
